### ISSUE TITLE
Why do we use `abstract` for all classes?

### ISSUE THREAD

**Issue by huan** [forbesmyester/stronger-typed-streams#1]
Hi, I'm trying to find a strongly typed stream module and I believe this repo is what I need after inspect the source code.

However, it seems that we have to create a child class from your typed `Transform` class so that it can be used.

What's the reason for the design like this?

Is there any way to use them directly just like the standard `stream` module?

Thanks for your great work, and I'm looking to your reply.

Huan

**Comment by forbesmyester** [comment]
Hi,

With Read and Write you need to implement the Read and Write. With Transform you'd want to actually do the Transform. It seems you need to add logic to make them work.

There may be some modelling advantage in Duplex being non-abstract but you don't __really__ need it in that case.

I think the best way to use these classes is to create a class inheriting and specifying the generics, because then it documents what it's doing `class Bakery extends Transform<Flour, Bread>` makes so much sense to me and this is how I would use the Node classes themselves.

Of course you could subclass and supply a transformation/read/write function which becomes a private method and leave the generics... This probably only makes sense for `Transform` though

Something like this?:

```typescript
class PluggableTransform<T1,T2> extends Transform<T> {

    constructor(private  f: (teeOne: T1) => T2, opts = {}, private encoding?: BufferEncoding) {
        super(opts);
    }

    // More stuff in here...
}
```

**Comment by huan** [comment]
Thanks for your reply!

In my situation, I'm using this workaround: make an empty child class for it:

https://github.com/wechaty/wechaty-puppet-hostie/blob/649a47bec3a2873e75337570d9975c5cf1011732/src/stream/typed-stream.ts#L5

and my use case is:

https://github.com/wechaty/wechaty-puppet-hostie/blob/35b69e910de2c84e26b9dae72065d48bd1c3009e/src/stream/file-box-helper.ts#L18-L28

So I'd like to suggest that we can make the `Transform` class non-abstract for convenience.

BTW: for `Readable` and `Writable`, it's ok because I only need the typing from them.

**Comment by forbesmyester** [comment]
Hey,

Thanks for your efforts in explaining what you wanted and why.

I've made the class non-abstract for you as well as an update to the newest Node LTS and fixed related typings / bit-rot issues that caused.

Released as a new 0.2.x series... Let me know if that works for you.

If you need to keep to earlier NodeJS typings I could back-port your removal of non-abstract to the 0.1.x releases if you need it.

Thanks

**Comment by huan** [comment]
It's great to have an instantiable `Transform` from our module, and the new 0.2 version helps my code to be cleaner a lot!

**Comment by forbesmyester** [comment]
Seems to be resolved so will close this issue.

Thanks for helping stronger-typed-streams be better.

**Comment by shellscape** [comment]
Just popping in to say that I was also looking for a drop-in replacement (for `Readable`) that was typed, and wasn't able to use the package because of the `abstract` requirement on `_read`. I'm simply piping one stream into a typed stream for type safety. Piping doesn't require managing anything, so no real need for it to be abstract there. I'll go with a copy/paste solution (with a copyright header of course), removing the `abstract`.
